// <auto-generated />
namespace ReportWebApp01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddFitbitAccount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFitbitAccount));
        
        string IMigrationMetadata.Id
        {
            get { return "201812270643029_Add-FitbitAccount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
